### PR TITLE
Rerendering to trigger r-base 3.6.1 build

### PR DESCRIPTION
**Pull request by fhoehle**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* ~[ ] Reset the build number to `0` (if the version changed)~
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by fhoehle** [comment]
@conda-forge-admin, please rerender

**Comment by fhoehle** [comment]
@conda-forge/r-kknn-feedstock please review/merge, thanks!

**Comment by fhoehle** [comment]
@conda-forge/r-kknn please review and merge. Thanks!

**Comment by dpryan79** [comment]
@conda-forge-admin please rerender

**Review by dpryan79 — APPROVED** [review]

**Pull request merged**
